# Copy csproj and restore for each project in the Instruments module
COPY ["Modules/Instruments/QuantumQube.Trading.Modules.Instruments.Api/QuantumQube.Trading.Modules.Instruments.Api.csproj", "Modules/Instruments/QuantumQube.Trading.Modules.Instruments.Api/"]
COPY ["Modules/Instruments/QuantumQube.Trading.Modules.Instruments.Domain/QuantumQube.Trading.Modules.Instruments.Domain.csproj", "Modules/Instruments/QuantumQube.Trading.Modules.Instruments.Domain/"]
COPY ["Modules/Instruments/QuantumQube.Trading.Modules.Instruments.Infrastructure/QuantumQube.Trading.Modules.Instruments.Infrastructure.csproj", "Modules/Instruments/QuantumQube.Trading.Modules.Instruments.Infrastructure/"]
COPY . .
